spring:
  application:
    name: book-store-consumer
    
server:
  port:9999
book:
  service:
    version: 1.0.0
    group: duowan

    

embedded:
  zookeeper:
    port: 2181

dubbo:
  registry:
    address: zookeeper://192.168.66.133:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache